"""simplify item images

Revision ID: ef7210c33ccf
Revises: fb1b75597610
Create Date: 2026-01-14 21:17:12.735703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef7210c33ccf'
down_revision: Union[str, Sequence[str], None] = 'fb1b75597610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    op.drop_index(op.f('uq_item_primary_image'), table_name='item_images', postgresql_where='(is_primary = true)')
    op.drop_table('item_images')
    op.add_column('items', sa.Column('image_path', sa.String(), nullable=True))
    op.alter_column('requisitions', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requisitions', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requisitions', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('requisitions', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'requisitions', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requisitions', type_='foreignkey')
    op.alter_column('requisitions', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('requisitions', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('requisitions', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requisitions', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('items', 'image_path')
    op.create_table('item_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('item_images_item_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('item_images_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('item_images_pkey'))
    )
    op.create_index(op.f('uq_item_primary_image'), 'item_images', ['item_id'], unique=True, postgresql_where='(is_primary = true)')
    op.create_table('test_table',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_table_pkey'))
    )
    # ### end Alembic commands ###
